export const TEST_DATA_2 = [
  'initial',
  'A',
  'X',
  'Lohnausweis - Certificat de salaire - Certificato di salario',
  'B',
  'Rentenbescheinigung - Attestation de rentes - Attestazione delle rendite',
  'c 756.4447.6214.31',
  '20.10.2001',
  'F',
  'X',
  'Unentgeltliche Beforderung naischen Wohn und Arbeitsort',
  'Transport gratuit entre le domicile et in lieu de travail',
  'AHV-Nr No AVS N ANS',
  'Geburtadatum Date de naissance Data di nescita',
  'Trasporto gratuito dal domicilio al luced di lavoro',
  'D 2023',
  'E 01.01.2023',
  '31.12.2023',
  'G',
  'X',
  'Kantinenverpflegung / Lunch-Checks',
  'Repes la cantine / chèques',
  'Jahr Année Anno',
  'won du dal',
  'bis al',
  'Pasti alla mensa buoni pasto',
  'H',
  'Bernhardsgrütter Andri',
  'Gossauerstrasse, 30',
  'Postfach 9246',
  '9246 Niederbüren',
  'Switzerland',
  'Nut gates Frankenbetries',
  'Que des montants entire',
  '1. Lohn',
  'soweit nicht unter Ziffer 2-7 aufzuhührer',
  '/ Rente',
  'Unicamente importi inter',
  'Salaire qui ne concerne pas les chitfree 247 cl- dessous / Rente',
  'Salario',
  'se nor da indicare sotto cifre da 2.a. DID sotto',
  '/ Rendita',
  "3'000",
  '2 Gehaltsnebenleistungen',
  '2.1 Verpflegung Unterkunft Pension logement - Vitto alloggio',
  '30',
  'Prestations salariales accession',
  'Prestazioni accessorie al salario 2.2 Privatenteil Geschäftsfahrzaug Part privés voitung de service Quota private automièès di servicio',
  '300',
  '2.3 Andere Autres Altre',
  'Art Genre Genere',
  '3. Unregelmässige Leistungen Prestations non périodiques Prestazioni aperiodiche',
  'Art Genre General',
  '4 Kapitalleistungen Prestations or capital Prestazioni in capitale',
  'Ar Genre Genere',
  '5. Betellgungsrechte gemäss Beiblatt Droits de participation selon annex Diritt di partecipazione secondo allezato',
  '+',
  "6 Verwaltungsratsentschädigunger Indemnités des membres de l'administration Indennità dei membri di consigt d'amministrazione",
  '7. Andere Leistungen Autres prestations Altre prestazioni',
  'As Genre Genere',
  'Billin',
  '8. Bruttolohn total / Rente Salaire brut total / Rente Salario lordo totals / Rendita',
  "3'330",
  '9 Beitrige AHV/V/EO/ALV/NBUV Cotinations AVS/AV/APG/AC/AANP Contributi AVS/AI/IPG/AD/AINP',
  '300',
  '10 Berufiche Vorsorge',
  '2 Sale',
  '10.1 Ordentliche Beiträge Cotinations ordinaires Contributi cripari',
  '300',
  'Prévoyance professionnelle',
  '2* piller',
  'Previdenza professionale',
  '2 pilastro',
  '10.2 Beiträge für der Einkauf Cotisations pour le rachat Contributi per riscatto',
  '30',
  '11. Nettolohn / Rente Salaire net / Rente Salario netto / Rendite',
  "2'700",
  "In die Steuererklärung Gbertragen A reporte sur la déclaration d'impôt De riportare nella dichiarazione de imposta",
  "12. Quellensteuerabzup Retenue de l'imp01 A la source Rhenuta d'imposta alla forte",
  '13 Spesenverpütungen - Allocations pour frain Indennità per spese',
  'Nicht im Bruttolohn Igemäse Zifter " enthalten Non comprises dans le salaire brut lau chittre N Non comprese nel salario lordo (sotto citra 81',
  '13.1 Effective Spesen',
  '13.1.1 Roise Verpflegung Übernachtung Voyage repas nubles Viaggio vitto alloggio',
  'X',
  'Frais effectifs',
  '13.1.2 Ubrige Autres Altre',
  'Spose effettive',
  'Art Genre General',
  '13.2 Pauschalsposer',
  '13.2.1 Repräsentation Représentation Rappresentance',
  '300',
  'Frair forfaitaires',
  'Spose forfettarie',
  '13.2.2 Auto Voiture Automobile',
  '400',
  '13.2.3 Ubriea Autres Altre',
  'Art Center General',
  '13.3 Beiträre an die Weiterbildung Contributions as perfectionnement Contributi per , perfezionamento',
  "2'000",
  '14. Weitere Gehaltsnebenieistunger',
  'Art',
  'Autres prestations salariales accessories',
  'Genre',
  'Altre prestazioni accessorie al salario',
  'Genere',
  '15. Bemerkungen',
  'Alles gut Kinderzulagen im Lohnausweis nicht enthalten. Auszahlung durch die Ausgleichskasse. U',
  'Observations',
  'Osservazioni',
  'mzugskosten von CHF 30.00 bezahlt. Einer von 1 Lohnausweiser',
  'I',
  'Ort und Datum Lieu et date Lungo e data',
  'Die Richtigkeit und Vollständigkeit bestifigt',
  'Andris Firma',
  'ink) genouer Anschrift und Telefonnummer des Arbeitgebers',
  'Andri Bernhardsgruetten',
  'Niederbueren, 08.05.2024',
  'Certifie exact et complet',
  '9246 Niederbueren',
  "K.C. adresse et numero de telephone asacts de l'employeur",
  'Tel. 0791915415',
  'Certificate matte completo',
  'compres indirizzo . numero di telefono matti del datore di lawpro',
  'Form. 11 df',
  '605.040.18N 01.21',
]
