export const TEST_DATA = [
  'initial',
  'A',
  'X',
  'Lohnausweis - Certificat de salaire - Certificato di salario',
  'B',
  'Rentenbescheinigung - Attestation de rentes - Attestazione delle rendite',
  'C',
  '756.0001.6886,74',
  'F',
  'Unentgeitliche Beförderun zwischen Wohn- und Arbetso it',
  'Transport gratuit entre le domicile et le lleu de travall',
  'AHV-Nr-NDAVS-N.AVS',
  'Neue AHV-Nr -Nouveau No AVS-Nuovo N AVS',
  'spoto gratuito dal domicilio al LOOD dilavoro',
  'D',
  '2016',
  'E',
  '01.01.16',
  '31.12.16',
  'Kantinernerpflegung/ Lunch-Checks',
  'G',
  'Rep 35 a la cantin chéques-repas',
  'Jahr-Annee-Anno',
  'von-du-dal',
  'bis-au -al',
  'Past alla mensa buon pasto',
  'H',
  'Frau',
  'Flavia Monini',
  'Im Tobelacher 15',
  '6034 Inwil',
  'Nur ganze FrankenbetGage',
  'Que des montants entiers',
  '1.',
  'Lohn',
  'soweit nicht unter Ziffer 2-7 autzuführen',
  '/ Rente',
  'Unicamente importi nten',
  'Salaire',
  'quine concerne pas RE d time 2 17 ol-',
  '/',
  'Rente',
  'Salario se non da Indicate sotto cife da2a7 plo sotto Rendita',
  "56'700",
  '2. Genatsrebeneistungen',
  '2.1 Verpflegung. Unterkunf Persion logement Vitto, alloggio',
  'Prestations salerales accessoires',
  'Prestazioniaccessage al saacia',
  '2.2 Privatanteil Geschäftswagen Part privee voture de service Quota privata automobile diservizio',
  '2.3 Andere Autres Altre',
  'Art-Genre General',
  '3. Unregelmässige Leistungen Prestations non périodiques Prestazioni aperiodiche',
  'Ait-Genre-Gene',
  '+',
  '4.',
  'Kapitalleistungen Prestations en capital Prestazioni capitale',
  'Art-Genre General',
  '5. Beteiligungsrechte gemäss Beiblatt Droits de participation selon annexe Diritt di partecipazione secondo allegato',
  '+',
  '6.',
  'indemnités des membres de fadminstation indennta deimembri di consiglio amministrazione',
  '+',
  '7. Andere Leistungen Autres prestations Altre prestazioni',
  '+',
  'Art-Genre General',
  '8. Bruttolohn total Rente Salaire brut total Rente Salario lordo totale / Rendita',
  '=',
  "56'700",
  '9. Beiträge AHV/VIEO/ALVINBUV Cotisations AVS/AJ/APG/AC/AANP Contributi AVS/AV/IPG/AD/AINP',
  '-',
  "4'238",
  '10. Berufiche Vorsorge',
  '2 Saule',
  '10.1 Ordentliche Beiträge Cotisations ordinaires Contributi ordinari',
  '-',
  '320',
  'Prévoyance',
  'professionnelle',
  "2' piller",
  'Previdenza professionale 2" plastic 10.2 Beiträge für den Einkauf Cotisations pour le rachat Contributi per il riscatto',
  '11. Nettolohn / Rente Salaire net/ Rente Salario netto / Rendita',
  '=',
  "52'142",
  "In die Steuererklärung übertragen A reporter sur la déclaration d'impôt Da riportare nella dichiarazione d'impost",
  "12. Quellensteuerabzug Retenue de l'impôtà la source Ritenuta d'imposta alla fonte",
  '13. Spesenvergütungen Allocations pour frais Indennità per spese',
  'Night in Bruttolohn (gemass Ziffer 8) enthater -Non compressians le salaire brut au chiffe -Non comprese nel salario lordo (sotto cifra 8)',
  '13.1 Effective Spesen 13.1.1 Reise Verpflegung. Ubernachtung Voyage repas, nuitées Viaggio, vitto alloggio',
  'Frais effectifs',
  '13.1.2',
  'Ubrige-Autres- Altre',
  'Spese effettive',
  'Genre -Genere',
  '13.2 Pauschalspesen',
  '13.2.1 Repräsentation Représentation Rappresentanza',
  'Frais fortaitaires',
  'Spese forfettarie',
  '13.2.2 Auto Voiture Automobile',
  '1323 Ubrige Autres Altre Pauschalspesen I',
  "6'000",
  'At Genre -Genere',
  '13.3 Beiträge an die Weiterbildung Contributions au perfectionnement Contributi per il erfezionamento',
  '14. Weitere Gehal tsnebenleistungen',
  'Art',
  'Autres prestations salariales accessoires Genre',
  'Altre prestazioni accessorie al salario',
  'Genere',
  '15. Bemerkungen',
  'Spesenreglement durch die Steuerverwaltung genehmigt 16.10.10',
  'Observations',
  'Osservazioni',
  'Beschäftigungsgrad 35%',
  'I',
  'Ort und Datum Lieu etdate Luogo e data',
  'Die Richtigkeit und Vollständigkeit bestätigt',
  'UID:CHE-107.693,634',
  'inkl genauer Anschrift und Telefonnummer 08 Arbs tgebers',
  'Gemeinde Ittwill',
  'Luzem, 17.05.17',
  'Certifé exact et complet',
  'Giuseppe Serio',
  "y.c adresse et nume de telephone exacts de l'employ eur",
  'Dorfplatz 8',
  'Certificato esatto completo',
  'Postfach',
  'compresindirizzo e nume di fono = del datom di',
  '6000 Luzern',
  '605,040.18 Form. 11 (25.8.2006)',
  'Tel:041929 90 10',
]
