import {
  AntDesign,
  Entypo,
  Feather,
  FontAwesome,
  FontAwesome5,
  FontAwesome6,
  MaterialIcons,
} from '@expo/vector-icons'
import { ReactNode } from 'react'
import { ScreenCategoryEnum, ScreenEnum, ScreenSubcategoryEnum } from './enums'
import { DataDefaults } from './types'

export const DATA_DEFAULTS: DataDefaults = {
  privateUnfall: {
    betrag: undefined,
  },
  spenden: {
    datum: undefined,
    bezeichnung: undefined,
    betrag: undefined,
  },
  schuldzinsen: {
    betrag: undefined,
  },
  verschuldet: {
    glauebiger: undefined,
    glauebigerAdresse: undefined,
    zinssatz: undefined,
    schuldhoehe: undefined,
    zinsenImJahr: undefined,
  },
  aktien: {
    dividendenertrag: undefined,
    beteiligungsquote: undefined,
    istQualifizierteBeteiligung: undefined,
  },
  geschaeftsOderKorporationsanteile: {
    bezeichnung: undefined,
    beteiligungsquote: undefined,
    ertrag: undefined,
    istQualifizierteBeteiligung: undefined,
  },
  verpflegungAufArbeit: {},
  wochenaufenthalt: {
    betrag: undefined,
    bezeichung: undefined,
    datum: undefined,
  },
  liegenschaften: {
    bezeichnung: undefined,
    ort: undefined,
    kanton: undefined,
    eigenmietwertOderMietertrag: undefined,
    unterhaltArt: undefined,
    unterhaltBetrag: undefined,
    istGeschaeftlich: undefined,
    vermoegenssteuerwert: undefined,
  },
  motorfahrzeug: {
    bezeichung: undefined,
    kaufjahr: undefined,
    kaufpreis: undefined,
  },
  aktien: {
    valorenNr: undefined,
    ISIN: undefined,
    gesellschaftTitel: undefined,
    staat: undefined,
    steuerwertEndeJahr: undefined,
    stueckzahl: undefined,
    waehrung: undefined,
    steuerwertProStueck: undefined,
  },
  bankkonto: {
    bankGesellschaft: undefined,
    kontoOderDepotNr: undefined,
    staat: undefined,
    bezeichnung: undefined,
    waehrung: undefined,
    steuerwertEndeJahr: undefined,
    zinsUeber200: undefined,
    zinsbetrag: undefined,
  },
  versicherungspraemie: {
    betrag: undefined,
  },
  saeule3a: {
    betrag: undefined,
  },
  // beitragArbeitgeberAusbildung: {
  //   betragArbeitGeber: undefined,
  // },
  schichtarbeit: {
    wieVieleTageImJahr: undefined,
    immerSchichtarbeit: undefined,
  },
  essenVerbilligungenVomArbeitgeber: {},
  autoMotorradArbeit: {
    fehlenVonOev: undefined,
    zeitersparnisUeber1h: undefined,
    staendigeBenutzungArbeitszeit: undefined,
    keinOevWeilKrankOderGebrechlich: undefined,
    geleastesFahrzeug: undefined,
  },
  autoMotorradArbeitWege: {
    arbeitsort: undefined,
    anzahlArbeitstage: undefined,
    anzahlKm: undefined,
    fahrtenProTag: undefined,
    rappenProKm: undefined,
  },
  veloArbeit: {},
  oevArbeit: {
    kosten: undefined,
  },
  geldVerdient: {
    von: undefined,
    bis: undefined,
    arbeitgeber: undefined,
    arbeitsort: undefined,
    urlaubstage: undefined,
    nettolohn: undefined,
    anzahlArbeitstage: undefined,
    uploadedLohnausweis: undefined,
  },
  verschuldet: {},
  geschaeftsOderKorporationsanteile: {},
  lebensOderRentenversicherung: {},
  erwerbsausfallentschaedigung: {},
  einkuenfteSozialversicherung: {},
  hatKinder: {},
  kinderImHaushalt: {
    vorname: undefined,
    nachname: undefined,
    geburtsdatum: undefined,
    inAusbildung: undefined,
    schuleOderLehrfirma: undefined,
    voraussichtlichBis: undefined,
    andererElternteilZahlt: undefined,
    unterhaltsbeitragProJahr: undefined,
  },
  kinderAusserhalb: {
    vorname: undefined,
    nachname: undefined,
    geburtsdatum: undefined,
    adresse: undefined,
    inAusbildung: undefined,
    schuleOderLehrfirma: undefined,
    voraussichtlichBis: undefined,
  },
  verheiratet: {},
  inZuerich: {},
  personData: {
    geburtsdatum: undefined,
    vorname: undefined,
    nachname: undefined,
    adresse: undefined,
    plz: undefined,
    stadt: undefined,
    land: undefined,
    zivilstand: undefined,
    email: undefined,
  },
  inAusbildung: {
    betrag: undefined,
    bezeichung: undefined,
    betragArbeitGeber: undefined,
  },
  krypto: {
    ertragMitVerrechnungssteuer: undefined,
    steuerwertProStueck: undefined,
    stueckzahl: undefined,
    steuerwert: undefined,
    waehrung: undefined,
    bank: undefined,
  },
  edelmetalle: {
    betrag: undefined,
  },
  bargeld: {
    betrag: undefined,
  },
  ahvIVsaeule2Selber: {
    betrag: undefined,
  },
  saeule2: {
    einkaufBetrag: undefined,
    ordentlichBetrag: undefined,
  },
  rueckzahlungBank: {
    nachname: undefined,
    vorname: undefined,
    iban: undefined,
  },
}

export const mapScreenCategoryToLabel: Record<ScreenCategoryEnum, string> = {
  [ScreenCategoryEnum.Eignung]: 'Eignung ',
  [ScreenCategoryEnum.Einkommen]: 'Einkommen',
  [ScreenCategoryEnum.Abzuege]: 'Abzuege',
  [ScreenCategoryEnum.Vermoegen]: 'Vermoegen',
  [ScreenCategoryEnum.Uebersicht]: 'Uebersicht',
}

export const mapScreenCategoryToIcon: Record<
  ScreenCategoryEnum,
  (params: { size: number; color: string }) => ReactNode
> = {
  [ScreenCategoryEnum.Eignung]: (props) => <FontAwesome6 name="person-circle-check" {...props} />,
  [ScreenCategoryEnum.Einkommen]: (props) => <FontAwesome5 name="money-bill" {...props} />,
  [ScreenCategoryEnum.Abzuege]: (props) => <AntDesign name="minus-square" {...props} />,
  [ScreenCategoryEnum.Vermoegen]: (props) => <FontAwesome name="bank" {...props} />,
  [ScreenCategoryEnum.Uebersicht]: (props) => <Entypo name="mail" {...props} />,
}

export const mapScreenEnumToCategory: Record<ScreenEnum, ScreenCategoryEnum> = {
  [ScreenEnum.PrivateUnfallAmount]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.PrivateUnfallYesNo]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.SpendenDetail]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.SpendenOverview]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.SpendenYesNo]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.SchuldzinsenYesNo]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.SchuldzinsenAmount]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.BargeldAmount]: ScreenCategoryEnum.Vermoegen,
  [ScreenEnum.BargeldYesNo]: ScreenCategoryEnum.Vermoegen,
  [ScreenEnum.EdelmetalleAmount]: ScreenCategoryEnum.Vermoegen,
  [ScreenEnum.EdelmetalleYesNo]: ScreenCategoryEnum.Vermoegen,
  [ScreenEnum.BankkontoDetail]: ScreenCategoryEnum.Vermoegen,
  [ScreenEnum.BankkontoHochladen]: ScreenCategoryEnum.Vermoegen,
  [ScreenEnum.BankkontoOverview]: ScreenCategoryEnum.Vermoegen,
  [ScreenEnum.AktienDetail]: ScreenCategoryEnum.Vermoegen,
  [ScreenEnum.AktienOverview]: ScreenCategoryEnum.Vermoegen,
  [ScreenEnum.AktienYesNo]: ScreenCategoryEnum.Vermoegen,
  [ScreenEnum.KryptoDetail]: ScreenCategoryEnum.Vermoegen,
  [ScreenEnum.KryptoOverview]: ScreenCategoryEnum.Vermoegen,
  [ScreenEnum.KryptoYesNo]: ScreenCategoryEnum.Vermoegen,
  [ScreenEnum.MotorfahrzeugDetail]: ScreenCategoryEnum.Vermoegen,
  [ScreenEnum.MotorfahrzeugYesNo]: ScreenCategoryEnum.Vermoegen,
  [ScreenEnum.LiegenschaftenYesNo]: ScreenCategoryEnum.Vermoegen,
  [ScreenEnum.LiegenschaftenOverview]: ScreenCategoryEnum.Vermoegen,
  [ScreenEnum.LiegenschaftenDetail]: ScreenCategoryEnum.Vermoegen,
  [ScreenEnum.Verschuldet]: ScreenCategoryEnum.Eignung,
  [ScreenEnum.VersicherungspraemieAmount]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.VersicherungspraemieYesNo]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.Saeule2YesNo]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.Saeule3aAmount]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.Saeule3aYesNo]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.InAusbildungYesNo]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.InAusbildungDetail]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.InAusbildungOverview]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.BeitragArbeitgeberAusbildungAmount]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.BeitragArbeitgeberAusbildungYesNo]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.VerpflegungAufArbeit]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.TageVerpflegungAufArbeit]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.Schichtarbeit]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.tageSchichtArbeit]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.EssenVerbilligungenVomArbeitgeber]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.Wochenaufenthalt]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.WochenaufenthaltDetail]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.WochenaufenthaltOverview]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.AutoMotorradArbeit]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.AutoMotorradArbeitCheckboxes]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.AutoMotorradArbeitWegeDetail]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.AutoMotorradArbeitWegeOverview]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.VeloArbeit]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.OevArbeit]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.OevArbeitKosten]: ScreenCategoryEnum.Abzuege,

  [ScreenEnum.GeldVerdient]: ScreenCategoryEnum.Einkommen,
  [ScreenEnum.GeldVerdientDetail]: ScreenCategoryEnum.Einkommen,
  [ScreenEnum.GeldVerdientOverview]: ScreenCategoryEnum.Einkommen,
  [ScreenEnum.LohnausweisUpload]: ScreenCategoryEnum.Einkommen,

  [ScreenEnum.GeschaeftsOderKorporationsanteile]: ScreenCategoryEnum.Eignung,
  [ScreenEnum.GeschaeftsOderKorporationsanteileOverview]: ScreenCategoryEnum.Einkommen,
  [ScreenEnum.GeschaeftsOderKorporationsanteileDetail]: ScreenCategoryEnum.Einkommen,
  [ScreenEnum.LebensOderRentenversicherung]: ScreenCategoryEnum.Eignung,
  [ScreenEnum.LebensOderRentenversicherungOverview]: ScreenCategoryEnum.Einkommen,
  [ScreenEnum.LebensOderRentenversicherungDetail]: ScreenCategoryEnum.Einkommen,
  [ScreenEnum.Erwerbsausfallentschädigung]: ScreenCategoryEnum.Eignung,
  [ScreenEnum.ErwerbsausfallentschaedigungOverview]: ScreenCategoryEnum.Einkommen,
  [ScreenEnum.ErwerbsausfallentschaedigungDetail]: ScreenCategoryEnum.Einkommen,
  [ScreenEnum.SozialUndVersicherungseinnahmen]: ScreenCategoryEnum.Eignung,
  [ScreenEnum.EinkuenfteSozialversicherungOverview]: ScreenCategoryEnum.Einkommen,
  [ScreenEnum.EinkuenfteSozialversicherungDetail]: ScreenCategoryEnum.Einkommen,
  [ScreenEnum.UnterhaltsbeitraegeYesNo]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.UnterhaltsbeitraegeEhegatten]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.UnterhaltsbeitraegeKinderOverview]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.UnterhaltsbeitraegeKinderDetail]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.UnterhaltsbeitraegeRentenleistungenOverview]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.UnterhaltsbeitraegeRentenleistungenDetail]: ScreenCategoryEnum.Abzuege,
  [ScreenEnum.Verschuldet]: ScreenCategoryEnum.Vermoegen,
  [ScreenEnum.VerschuldetOverview]: ScreenCategoryEnum.Vermoegen,
  [ScreenEnum.VerschuldetDetail]: ScreenCategoryEnum.Vermoegen,
  [ScreenEnum.HatKinder]: ScreenCategoryEnum.Eignung,
  [ScreenEnum.KinderImHaushaltYesNo]: ScreenCategoryEnum.Eignung,
  [ScreenEnum.KinderImHaushaltOverview]: ScreenCategoryEnum.Eignung,
  [ScreenEnum.KinderImHaushaltDetail]: ScreenCategoryEnum.Eignung,
  [ScreenEnum.KinderAusserhalbYesNo]: ScreenCategoryEnum.Eignung,
  [ScreenEnum.KinderAusserhalbOverview]: ScreenCategoryEnum.Eignung,
  [ScreenEnum.KinderAusserhalbDetail]: ScreenCategoryEnum.Eignung,
  [ScreenEnum.Verheiratet]: ScreenCategoryEnum.Eignung,
  [ScreenEnum.LivingInZurich]: ScreenCategoryEnum.Eignung,

  [ScreenEnum.Uebersicht]: ScreenCategoryEnum.Uebersicht,
  [ScreenEnum.Eignungsfragen]: ScreenCategoryEnum.Eignung,
  [ScreenEnum.Einkuenfte]: ScreenCategoryEnum.Einkommen,
  [ScreenEnum.Vermoegen]: ScreenCategoryEnum.Vermoegen,
  [ScreenEnum.Abzuege]: ScreenCategoryEnum.Abzuege,

  [ScreenEnum.LohnausweisHochladen]: ScreenCategoryEnum.Einkommen,

  [ScreenEnum.GeneratePdf]: ScreenCategoryEnum.Uebersicht,
  [ScreenEnum.Personalien]: ScreenCategoryEnum.Uebersicht,
  [ScreenEnum.RueckzahlungBank]: ScreenCategoryEnum.Uebersicht,
}

export const mapScreenEnumToSubcategory: Partial<Record<ScreenEnum, ScreenSubcategoryEnum>> = {
  [ScreenEnum.GeldVerdient]: ScreenSubcategoryEnum.SubLohn,
  [ScreenEnum.GeldVerdientDetail]: ScreenSubcategoryEnum.SubLohn,
  [ScreenEnum.GeldVerdientOverview]: ScreenSubcategoryEnum.SubLohn,
  [ScreenEnum.LohnausweisHochladen]: ScreenSubcategoryEnum.SubLohn,
  [ScreenEnum.OevArbeit]: ScreenSubcategoryEnum.SubOevArbeit,
  [ScreenEnum.OevArbeitKosten]: ScreenSubcategoryEnum.SubOevArbeit,
  [ScreenEnum.AutoMotorradArbeit]: ScreenSubcategoryEnum.SubAutoMotorradArbeit,
  [ScreenEnum.AutoMotorradArbeitCheckboxes]: ScreenSubcategoryEnum.SubAutoMotorradArbeit,
  [ScreenEnum.AutoMotorradArbeitWegeDetail]: ScreenSubcategoryEnum.SubAutoMotorradArbeit,
  [ScreenEnum.AutoMotorradArbeitWegeOverview]: ScreenSubcategoryEnum.SubAutoMotorradArbeit,
  [ScreenEnum.VerpflegungAufArbeit]: ScreenSubcategoryEnum.SubVerpflegungAufArbeit,
  [ScreenEnum.TageVerpflegungAufArbeit]: ScreenSubcategoryEnum.SubVerpflegungAufArbeit,
  [ScreenEnum.Schichtarbeit]: ScreenSubcategoryEnum.SubSchichtarbeit,
  [ScreenEnum.tageSchichtArbeit]: ScreenSubcategoryEnum.SubSchichtarbeit,
  [ScreenEnum.Wochenaufenthalt]: ScreenSubcategoryEnum.SubWochenaufenthalt,
  [ScreenEnum.WochenaufenthaltDetail]: ScreenSubcategoryEnum.SubWochenaufenthalt,
  [ScreenEnum.WochenaufenthaltOverview]: ScreenSubcategoryEnum.SubWochenaufenthalt,
  [ScreenEnum.InAusbildungOverview]: ScreenSubcategoryEnum.SubAusWeiterbildung,
  [ScreenEnum.InAusbildungYesNo]: ScreenSubcategoryEnum.SubAusWeiterbildung,
  [ScreenEnum.InAusbildungDetail]: ScreenSubcategoryEnum.SubAusWeiterbildung,
  [ScreenEnum.BeitragArbeitgeberAusbildungAmount]: ScreenSubcategoryEnum.SubAusWeiterbildung,
  [ScreenEnum.BeitragArbeitgeberAusbildungYesNo]: ScreenSubcategoryEnum.SubAusWeiterbildung,
  [ScreenEnum.Saeule3aAmount]: ScreenSubcategoryEnum.SubSaeule3a,
  [ScreenEnum.Saeule3aYesNo]: ScreenSubcategoryEnum.SubSaeule3a,
  [ScreenEnum.VersicherungspraemieYesNo]: ScreenSubcategoryEnum.SubVersicherungspraemien,
  [ScreenEnum.VersicherungspraemieAmount]: ScreenSubcategoryEnum.SubVersicherungspraemien,
  [ScreenEnum.PrivateUnfallYesNo]: ScreenSubcategoryEnum.SubVersicherungspraemien,
  [ScreenEnum.PrivateUnfallAmount]: ScreenSubcategoryEnum.SubVersicherungspraemien,
  [ScreenEnum.SpendenYesNo]: ScreenSubcategoryEnum.SubSpenden,
  [ScreenEnum.SpendenDetail]: ScreenSubcategoryEnum.SubSpenden,
  [ScreenEnum.SpendenOverview]: ScreenSubcategoryEnum.SubSpenden,
  [ScreenEnum.BargeldYesNo]: ScreenSubcategoryEnum.SubBargeld,
  [ScreenEnum.BargeldAmount]: ScreenSubcategoryEnum.SubBargeld,
  [ScreenEnum.SchuldzinsenYesNo]: ScreenSubcategoryEnum.SubSchulden,
  [ScreenEnum.SchuldzinsenAmount]: ScreenSubcategoryEnum.SubSchulden,
  [ScreenEnum.Verschuldet]: ScreenSubcategoryEnum.SubSchulden,
  [ScreenEnum.VerschuldetOverview]: ScreenSubcategoryEnum.SubSchulden,
  [ScreenEnum.VerschuldetDetail]: ScreenSubcategoryEnum.SubSchulden,
  [ScreenEnum.UnterhaltsbeitraegeYesNo]: ScreenSubcategoryEnum.SubUnterhaltsbeitraege,
  [ScreenEnum.UnterhaltsbeitraegeEhegatten]: ScreenSubcategoryEnum.SubUnterhaltsbeitraege,
  [ScreenEnum.UnterhaltsbeitraegeKinderOverview]: ScreenSubcategoryEnum.SubUnterhaltsbeitraege,
  [ScreenEnum.UnterhaltsbeitraegeKinderDetail]: ScreenSubcategoryEnum.SubUnterhaltsbeitraege,
  [ScreenEnum.UnterhaltsbeitraegeRentenleistungenOverview]: ScreenSubcategoryEnum.SubUnterhaltsbeitraege,
  [ScreenEnum.UnterhaltsbeitraegeRentenleistungenDetail]: ScreenSubcategoryEnum.SubUnterhaltsbeitraege,
  [ScreenEnum.SozialUndVersicherungseinnahmen]: ScreenSubcategoryEnum.SubSozialversicherungen,
  [ScreenEnum.EinkuenfteSozialversicherungOverview]: ScreenSubcategoryEnum.SubSozialversicherungen,
  [ScreenEnum.EinkuenfteSozialversicherungDetail]: ScreenSubcategoryEnum.SubSozialversicherungen,
  [ScreenEnum.Erwerbsausfallentschädigung]: ScreenSubcategoryEnum.SubSozialversicherungen,
  [ScreenEnum.ErwerbsausfallentschaedigungOverview]: ScreenSubcategoryEnum.SubSozialversicherungen,
  [ScreenEnum.ErwerbsausfallentschaedigungDetail]: ScreenSubcategoryEnum.SubSozialversicherungen,
  [ScreenEnum.LebensOderRentenversicherung]: ScreenSubcategoryEnum.SubSozialversicherungen,
  [ScreenEnum.LebensOderRentenversicherungOverview]: ScreenSubcategoryEnum.SubSozialversicherungen,
  [ScreenEnum.LebensOderRentenversicherungDetail]: ScreenSubcategoryEnum.SubSozialversicherungen,
  [ScreenEnum.GeschaeftsOderKorporationsanteile]: ScreenSubcategoryEnum.SubGeschaeftsanteile,
  [ScreenEnum.GeschaeftsOderKorporationsanteileOverview]: ScreenSubcategoryEnum.SubGeschaeftsanteile,
  [ScreenEnum.GeschaeftsOderKorporationsanteileDetail]: ScreenSubcategoryEnum.SubGeschaeftsanteile,
  [ScreenEnum.EdelmetalleYesNo]: ScreenSubcategoryEnum.SubEdelmetall,
  [ScreenEnum.EdelmetalleAmount]: ScreenSubcategoryEnum.SubEdelmetall,
  [ScreenEnum.BankkontoHochladen]: ScreenSubcategoryEnum.SubBankkonto,
  [ScreenEnum.BankkontoDetail]: ScreenSubcategoryEnum.SubBankkonto,
  [ScreenEnum.BankkontoOverview]: ScreenSubcategoryEnum.SubBankkonto,
  [ScreenEnum.AktienYesNo]: ScreenSubcategoryEnum.SubAktien,
  [ScreenEnum.AktienOverview]: ScreenSubcategoryEnum.SubAktien,
  [ScreenEnum.AktienDetail]: ScreenSubcategoryEnum.SubAktien,
  [ScreenEnum.KryptoYesNo]: ScreenSubcategoryEnum.SubKrypto,
  [ScreenEnum.KryptoDetail]: ScreenSubcategoryEnum.SubKrypto,
  [ScreenEnum.KryptoOverview]: ScreenSubcategoryEnum.SubKrypto,
  [ScreenEnum.MotorfahrzeugYesNo]: ScreenSubcategoryEnum.SubMotorfahrzeug,
  [ScreenEnum.MotorfahrzeugDetail]: ScreenSubcategoryEnum.SubMotorfahrzeug,
  [ScreenEnum.LiegenschaftenYesNo]: ScreenSubcategoryEnum.SubLiegenschaften,
  [ScreenEnum.LiegenschaftenOverview]: ScreenSubcategoryEnum.SubLiegenschaften,
  [ScreenEnum.LiegenschaftenDetail]: ScreenSubcategoryEnum.SubLiegenschaften,

  // [ScreenEnum.CategoryOne]: undefined,
  // [ScreenEnum.Test]: undefined,
}

export const mapSubcategoryToLabel: Record<ScreenSubcategoryEnum, string> = {
  [ScreenSubcategoryEnum.SubEignung]: 'Eignung',
  [ScreenSubcategoryEnum.SubLohn]: 'Lohn',
  [ScreenSubcategoryEnum.SubOevArbeit]: 'ÖV zur Arbeit',
  [ScreenSubcategoryEnum.SubAutoMotorradArbeit]: 'Auto/Motorrad zur Arbeit',

  [ScreenSubcategoryEnum.SubVerpflegungAufArbeit]: 'Verpflegung auf Arbeit',
  [ScreenSubcategoryEnum.SubSchichtarbeit]: 'Schichtarbeit',
  [ScreenSubcategoryEnum.SubWochenaufenthalt]: 'Wochenaufenthalt',
  [ScreenSubcategoryEnum.SubAusWeiterbildung]: 'Berufsorientierte Aus- und Weiterbildung',
  [ScreenSubcategoryEnum.SubSaeule3a]: 'Säule 3a',
  [ScreenSubcategoryEnum.SubVersicherungspraemien]: 'Versicherungsprämien',
  [ScreenSubcategoryEnum.SubSpenden]: 'Spenden',
  [ScreenSubcategoryEnum.SubBargeld]: 'Bargeld',
  [ScreenSubcategoryEnum.SubEdelmetall]: 'Edelmetall',
  [ScreenSubcategoryEnum.SubBankkonto]: 'Bankkonten',
  [ScreenSubcategoryEnum.SubAktien]: 'Aktien',
  [ScreenSubcategoryEnum.SubKrypto]: 'Kryptowährungen',
  [ScreenSubcategoryEnum.SubMotorfahrzeug]: 'Motorfahrzeug',
  [ScreenSubcategoryEnum.SubSchulden]: 'Schulden',
  [ScreenSubcategoryEnum.SubLiegenschaften]: 'Liegenschaften',
  [ScreenSubcategoryEnum.SubUnterhaltsbeitraege]: 'Unterhaltsbeiträge',
  [ScreenSubcategoryEnum.SubSozialversicherungen]: 'Sozialversicherungen',
  [ScreenSubcategoryEnum.SubGeschaeftsanteile]: 'Geschäftsanteile',
}

export const mapCategoryToCategoryOverviewScreen: Record<ScreenCategoryEnum, ScreenEnum> = {
  [ScreenCategoryEnum.Abzuege]: ScreenEnum.Abzuege,
  [ScreenCategoryEnum.Eignung]: ScreenEnum.Eignungsfragen,
  [ScreenCategoryEnum.Einkommen]: ScreenEnum.GeldVerdientOverview,
  [ScreenCategoryEnum.Vermoegen]: ScreenEnum.Vermoegen,
  [ScreenCategoryEnum.Uebersicht]: ScreenEnum.Uebersicht,
}
