export enum ScreenEnum {
  LivingInZurich = 'LivingInZurich',
  Verheiratet = 'Verheiratet',
  HatKinder = 'HatKinder',
  SozialUndVersicherungseinnahmen = 'SozialUndVersicherungseinnahmen',
  Erwerbsausfallentschädigung = 'Erwerbsausfallentschädigung',
  LebensOderRentenversicherung = 'LebensOderRentenversicherung',
  GeschaeftsOderKorporationsanteile = 'GeschaeftsOderKorporationsanteile',
  LohnausweisHochladen = 'LohnausweisHochladen',
  GeldVerdient = 'GeldVerdient',
  GeldVerdientDetail = 'GeldVerdientDetail',
  GeldVerdientOverview = 'GeldVerdientOverview',
  LohnausweisUpload = 'LohnausweisUpload',
  OevArbeit = 'OevArbeit',
  OevArbeitKosten = 'OevArbeitKosten',
  VeloArbeit = 'VeloArbeit',
  AutoMotorradArbeit = ' AutoMotorradArbeit',
  AutoMotorradArbeitCheckboxes = 'AutoMotorradArbeitCheckboxes',
  AutoMotorradArbeitWegeDetail = 'AutoMotorradArbeitWegeDetail',
  AutoMotorradArbeitWegeOverview = 'AutoMotorradArbeitWegeOverview',

  VerpflegungAufArbeit = 'VerpflegungAufArbeit',
  TageVerpflegungAufArbeit = 'TageVerpflegungAufArbeit',
  EssenVerbilligungenVomArbeitgeber = 'EssenVerbilligungenVomArbeitgeber',

  Schichtarbeit = 'Schichtarbeit',
  tageSchichtArbeit = 'Tageschichtarbeit',
  Wochenaufenthalt = 'Wochenaufenthalt',
  WochenaufenthaltDetail = 'WochenaufenthaltDetail',
  WochenaufenthaltOverview = 'WochenaufenthaltOverview',
  BeitragArbeitgeberAusbildungYesNo = 'BeitragArbeitgeberAusbildungYesNo',
  BeitragArbeitgeberAusbildungAmount = ' BeitragArbeitgeberAusbildungAmount',
  Saeule2YesNo = 'Saeule2YesNo',
  Saeule3aYesNo = 'Saeule3aYesNo',
  Saeule3aAmount = 'Saeule3aAmount',
  VersicherungspraemieYesNo = 'VersicherungspraemieYesNo',
  VersicherungspraemieAmount = 'VersicherungspraemieAmount',
  PrivateUnfallYesNo = 'PrivateUnfallYesNo',
  PrivateUnfallAmount = 'PrivateUnfallAmount',
  SpendenYesNo = 'SpendenYesNo',
  SpendenDetail = 'SpendenDetail',
  SpendenOverview = 'SpendenOverview',
  BargeldYesNo = 'BargeldYesNo',
  BargeldAmount = 'BargeldAmount',
  EdelmetalleYesNo = 'EdelmetalleYesNo',
  EdelmetalleAmount = 'EdelmetalleAmount',
  BankkontoHochladen = 'BankkontoHochladen',
  BankkontoOverview = 'BankkontoOverview',
  BankkontoDetail = 'BankkontoDetail',
  AktienYesNo = 'AktienYesNo',
  AktienDetail = 'AktienDetail',
  AktienOverview = 'AktienOverview',
  Verschuldet = 'Verschuldet',
  VerschuldetOverview = 'VerschuldetOverview',
  VerschuldetDetail = 'VerschuldetDetail',
  SchuldzinsenYesNo = 'SchuldzinsenYesNo',
  SchuldzinsenAmount = 'SchuldzinsenAmount',
  UnterhaltsbeitraegeYesNo = 'UnterhaltsbeitraegeYesNo',
  UnterhaltsbeitraegeEhegatten = 'UnterhaltsbeitraegeEhegatten',
  UnterhaltsbeitraegeKinderOverview = 'UnterhaltsbeitraegeKinderOverview',
  UnterhaltsbeitraegeKinderDetail = 'UnterhaltsbeitraegeKinderDetail',
  UnterhaltsbeitraegeRentenleistungenOverview = 'UnterhaltsbeitraegeRentenleistungenOverview',
  UnterhaltsbeitraegeRentenleistungenDetail = 'UnterhaltsbeitraegeRentenleistungenDetail',
  EinkuenfteSozialversicherungOverview = 'EinkuenfteSozialversicherungOverview',
  EinkuenfteSozialversicherungDetail = 'EinkuenfteSozialversicherungDetail',
  ErwerbsausfallentschaedigungOverview = 'ErwerbsausfallentschaedigungOverview',
  ErwerbsausfallentschaedigungDetail = 'ErwerbsausfallentschaedigungDetail',
  LebensOderRentenversicherungOverview = 'LebensOderRentenversicherungOverview',
  LebensOderRentenversicherungDetail = 'LebensOderRentenversicherungDetail',
  GeschaeftsOderKorporationsanteileOverview = 'GeschaeftsOderKorporationsanteileOverview',
  GeschaeftsOderKorporationsanteileDetail = 'GeschaeftsOderKorporationsanteileDetail',
  KryptoYesNo = 'KryptoYesNo',
  KryptoDetail = 'KryptoDetail',
  KryptoOverview = 'KryptoOverview',
  MotorfahrzeugYesNo = 'MotorfahrzeugYesNo',
  MotorfahrzeugDetail = 'MotorfahrzeugDetail',

  LiegenschaftenYesNo = 'LiegenschaftenYesNo',
  LiegenschaftenOverview = 'LiegenschaftenOverview',
  LiegenschaftenDetail = 'LiegenschaftenDetail',

  InAusbildungYesNo = 'InAusbildungYesNo',
  InAusbildungOverview = 'InAusbildungOverview',
  InAusbildungDetail = 'InAusbildungDetail',

  KinderImHaushaltYesNo = 'KinderImHaushaltYesNo',
  KinderImHaushaltOverview = 'KinderImHaushaltOverview',
  KinderImHaushaltDetail = 'KinderImHaushaltDetail',

  KinderAusserhalbYesNo = 'KinderAusserhalbYesNo',
  KinderAusserhalbOverview = 'KinderAusserhalbOverview',
  KinderAusserhalbDetail = 'KinderAusserhalbDetail',

  // CategoryOne = 'CategoryOne',
  // PersonalData = 'PersonalData',

  // Done = 'Done',
  // Rejected = 'Rejected',
  // Placeholder = 'Placeholder',
  Personalien = 'Personalien',
  RueckzahlungBank = 'RueckzahlungBank',
  GeneratePdf = 'GeneratePdf',

  Eignungsfragen = 'Eignungsfragen',
  Einkuenfte = 'Einkuenfte',
  Abzuege = 'Abzuege',
  Vermoegen = 'Vermoegen',
  Uebersicht = 'Uebersicht',
}

export enum ScreenTypeEnum {
  YesNo = 'YesNo',
  ObjForm = 'ObjForm',
  ArrayForm = 'ArrayForm',
  ArrayOverview = 'ArrayOverview',
  CategoryOverview = 'CategoryOverview',

  ScanOrUploadObj = 'ScanOrUploadObj',
  ScanOrUploadArray = 'ScanOrUploadArray',
  ScanOrUploadArrayBankkonto = 'ScanOrUploadArrayBankkonto',
  GeneratePdf = 'GeneratePdf',
}

export enum ScreenSubcategoryEnum {
  SubEignung = 'SubEignung',
  SubOevArbeit = 'SubOevArbeit',
  SubAutoMotorradArbeit = 'SubAutoMotorradArbeit',
  SubVerpflegungAufArbeit = 'SubVerpflegungAufArbeit',
  SubSchichtarbeit = 'SubSchichtarbeit',
  SubWochenaufenthalt = ' SubWochenaufenthalt',
  SubAusWeiterbildung = 'SubAusWeiterbildung',
  SubSaeule3a = 'SubSaeule3a',
  SubVersicherungspraemien = 'SubVersicherungspraemien',
  SubSpenden = 'SubSpenden',
  SubBargeld = 'SubBargeld',
  SubEdelmetall = 'SubEdelmetall',
  SubBankkonto = 'SubBankkonto',
  SubAktien = 'SubAktien',
  SubKrypto = 'SubKrypto',
  SubMotorfahrzeug = 'SubMotorfahrzeug',
  SubSchulden = 'SubSchulden',
  SubLiegenschaften = 'SubLiegenschaften',
  SubLohn = 'SubLohn',
  SubUnterhaltsbeitraege = 'SubUnterhaltsbeitraege',
  SubSozialversicherungen = 'SubSozialversicherungen',
  SubWertschriftenertrag = 'SubWertschriftenertrag',
}

export enum ScreenCategoryEnum {
  Eignung = 'Eignung',
  Einkommen = 'Einkommen',
  Abzuege = 'Abzuege',
  Vermoegen = 'Vermoegen',
  Uebersicht = 'Uebersicht',
}

export enum TaxReturnScreen {
  Flow = 'Flow',
  Overview = 'Overview',
}
